### PR TITLE
Handle closing of channels

### LINKED ISSUE #555: Interchain accounts testing
Interchain account supports needs testing in Relayer. 

This may or may not need to be addressed also:
https://github.com/strangelove-ventures/relayer/issues/48

### LINKED ISSUE #858: Account for changes in channel state
In interchain accounts, if a packet times out, then the channel end moves to a `CLOSED` state and the channel will need to be re-opened.

Currently we handle the timing out part correctly but I believe we need to update the state for the channel at that point. Right now if we time out a packet on an `ORDERED` channel with the relayer we will see the packet timeout correctly and can observe that the one end of the channel becomes `CLOSED` but we don't handle the re-opening of said channel correctly. Essentially you will see logs like this:
```
ts=2022-07-19T20:00:55.774868Z lvl=info msg="Error building or broadcasting transaction" provider_type=cosmos chain_id=test-2 attempt=1 max_attempts=5 error="rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: channel open try callback failed: existing active channel channel-0 for portID icahost is already OPEN: active channel already set for this owner: invalid request"
```

Upon manually querying the channel state you can verify that it is closed:
```
channels:
- channel_id: channel-0
  connection_hops:
  - connection-0
  counterparty:
    channel_id: channel-0
    port_id: icahost
  ordering: ORDER_ORDERED
  port_id: icacontroller-cosmos1m9l358xunhhwds0568za49mzhvuxx9uxre5tud
  state: STATE_CLOSED
  version: '{"version":"ics27-1","controller_connection_id":"connection-0","host_connection_id":"connection-0","address":"cosmos15ccshhmp0gsx29qpqq6g4zmltnnvgmyu9ueuadh9y2nc5zj0szls5gtddz","encoding":"proto3","tx_type":"sdk_multi_msg"}'
height:
  revision_height: "175"
  revision_number: "1"
pagination:
  next_key: null
  total: "0"
```

To reproduce the issue:
- Checkout main branch on the relayer and `make install`
- Clone down the ICA demo repo here https://github.com/jtieri/interchain-accounts-demo 
- Run `make init-golang-rly` from the root directory of the ICA demo repo

NOTE: relayer output is redirected to `./data/rly-0.log`

### PR DESCRIPTION
**Pull request by jtieri**
We were not handling channel closures correctly in the relayer due to some confusion surrounding the packet flow for channel close handshakes. Now we should be handling the channel closure correctly for `ORDERED` channels which is a requirement for interchain accounts.

__Note:__
I don't believe this will work for `UNORDERED` channels since we are only sending `MsgChannelCloseConfirm` when a packet times out on an `ORDERED` channel. I think to get this working for `UNORDERED` channels we would need to check the channel state on both ends and if we see one end is closed then we send `MsgChannelCloseConfirm` to the counterparty channel-end. Either way, that is outside the scope of this PR.

Closes #858 
Closes #555

### CODE REVIEW

File: relayer/processor/path_processor_internal.go [hunk 1]
```diff
@@ -869,29 +932,59 @@ func (pp *PathProcessor) connectionMessagesToSend(pathEnd1ConnectionHandshakeRes
...
 	}
 
-	return pathEnd1PacketMessages, pathEnd2PacketMessages
+	return pathEnd1PacketMessages, pathEnd2PacketMessages, pathEnd1ChannelMessage, pathEnd2ChannelMessage
+}
+
+// orderFromString parses a string into a channel order byte
+func orderFromString(order string) chantypes.Order {
+	switch strings.ToUpper(order) {
+	case "UNORDERED":
```
Comment (agouin) [inline relayer/processor/path_processor_internal.go]: `chantypes.UNORDERED.String()` here and `ORDERED`?

Also maybe this should go in `types_internal.go`?

File: relayer/processor/path_end_runtime.go [hunk 2]
```diff
@@ -493,9 +493,13 @@ func (pathEnd *pathEndRuntime) shouldSendChannelMessage(message channelIBCMessag
 			toDeleteCounterparty[chantypes.EventTypeChannelOpenAck] = []ChannelKey{counterpartyKey}
 			toDelete[chantypes.EventTypeChannelOpenTry] = []ChannelKey{channelKey}
 			toDeleteCounterparty[chantypes.EventTypeChannelOpenInit] = []ChannelKey{counterpartyKey.msgInitKey()}
+		case chantypes.EventTypeChannelCloseConfirm:
+			toDeleteCounterparty[chantypes.EventTypeChannelCloseInit] = []ChannelKey{counterpartyKey}
```
Comment (agouin) [inline relayer/processor/path_end_runtime.go:500]: We also need to delete all of the relevant packet flow messages in this flow for the relative channel key, e.g:
- `toDeleteCounterpartyPacket[EventTypeTimeoutPacket]`
- `toDeletePacket[chantypes.EventTypeSendPacket]`

these can be constructed by iterating over either `pathEnd` or `counterparty` `messagesCache.PacketFlow[channelKey or counterpartyKey, respectively]`

File: relayer/chains/cosmos/message_handlers.go [hunk 3]
```diff
@@ -61,7 +61,7 @@ func (ccp *CosmosChainProcessor) handleChannelMessage(eventType string, ci provi
 		ccp.channelStateCache[channelKey] = false
 	case chantypes.EventTypeChannelOpenAck, chantypes.EventTypeChannelOpenConfirm:
 		ccp.channelStateCache[channelKey] = true
-	case chantypes.EventTypeChannelCloseInit, chantypes.EventTypeChannelCloseConfirm:
+	case chantypes.EventTypeChannelCloseConfirm:
```
Comment (agouin) [inline relayer/chains/cosmos/message_handlers.go:64]: Is there a reason we don't want to consider the channel closed upon observing a committed `EventTypeChannelCloseInit`?

File: relayer/processor/path_processor_internal.go (hunk 1 above)
Comment (jtieri) [reply relayer/processor/path_processor_internal.go]: Good idea, I brought this in a bit haphazardly.

File: relayer/processor/path_end_runtime.go (hunk 2 above)
Comment (jtieri) [reply relayer/processor/path_end_runtime.go:500]: AH okay. I misread this the first time I went through it this morning but that makes sense. Will get this adjusted in a bit here.

File: relayer/chains/cosmos/message_handlers.go (hunk 3 above)
Comment (jtieri) [reply relayer/chains/cosmos/message_handlers.go:64]: It seemed like we came to the conclusion that `MsgChannelCloseInit` is never actually emitted or sent over the wire, but is an internal message type that a module uses to close the channel end on its side. I think we could purge all references to it in the code.

Comment (jtieri) [reply relayer/chains/cosmos/message_handlers.go:64]: `MsgTimeoutOnClose` may be a similar internal type that a module can use to cancel out pending packets upon a channel closure.

Comment (agouin) [reply relayer/chains/cosmos/message_handlers.go:64]: The `MsgChannelCloseInit` is not included in this particular channel close flow (`MsgTimeout` on an ordered channel), but I'm not sure that it is unnecessary for all channel closures. We can remove it as it relates to the scope of this PR though. I created #868 to follow up

File: relayer/processor/path_end_runtime.go [hunk 4]
```diff
@@ -493,9 +496,33 @@ func (pathEnd *pathEndRuntime) shouldSendChannelMessage(message channelIBCMessag
...
+			toDelete[chantypes.EventTypeChannelCloseConfirm] = []ChannelKey{channelKey}
+
+			// Delete relevant send packet messages for this channel key if we are operating on an
+			// ordered channel.
+			for _, pCache := range pathEnd.messageCache.PacketFlow[channelKey] {
```
Comment (agouin) [inline relayer/processor/path_end_runtime.go]: Here, rather than iterating on the `PacketMessagesCache` which may not exist, we should check if `pathEnd.messageCache.PacketFlow[channelKey]` exists. If it does exist, we should check if `chantypes.EventTypeSendPacket` exists within that `PacketMessagesCache`. If the type does exist, then we should iterate over the `PacketSequenceCache` (`pCache` as you have it here) and append those sequences (currently ignored with `_`) to `toDeletePacket[chantypes.EventTypeSendPacket]`.

A similar thing should be done for the `chantypes.EventTypeTimeoutPacket` for the `counterparty` below this `L515-L521`.

File: relayer/processor/path_end_runtime.go [hunk 5]
```diff
@@ -493,9 +496,33 @@ func (pathEnd *pathEndRuntime) shouldSendChannelMessage(message channelIBCMessag
...
+					if p.ChannelOrder == chantypes.ORDERED.String() {
+						toDeleteCounterpartyPacket[chantypes.EventTypeTimeoutPacket] = []uint64{}
+					}
+				}
+			}
 		}
+
 		// delete in progress send for this specific message
-		pathEnd.channelProcessing.deleteMessages(map[string][]ChannelKey{eventType: []ChannelKey{channelKey}})
+		pathEnd.channelProcessing.deleteMessages(map[string][]ChannelKey{eventType: {channelKey}})
```
Comment (agouin) [inline relayer/processor/path_end_runtime.go:532]: Down here we should call `pathEnd.messageCache.PacketFlow.DeleteMessages(toDeletePacket)` and same for `counterparty`/`toDeleteCounterpartyPacket` to delete the retained packet flow messages that we are giving up on.

File: relayer/processor/path_end_runtime.go (hunk 4 above)
Comment (jtieri) [reply relayer/processor/path_end_runtime.go]: Done!

File: relayer/processor/path_processor_internal.go [hunk 6]
```diff
@@ -512,25 +552,43 @@ func (pp *PathProcessor) processLatestMessages(ctx context.Context, messageLifec
 	pathEnd2ProcessRes := make([]pathEndPacketFlowResponse, len(channelPairs))
 
 	for i, pair := range channelPairs {
+		var pathEnd1ChannelCloseConfirm, pathEnd2ChannelCloseConfirm *provider.ChannelInfo
+		pathEnd1ChanCloseConfirmMsgs, ok := pp.pathEnd1.messageCache.ChannelHandshake[chantypes.EventTypeChannelCloseConfirm]
```
Comment (agouin) [inline relayer/processor/path_processor_internal.go]: looks like these can slim down to do the `if` on the same line

**Review by agouin — APPROVED** [review]
Looks good!
