### PR TITLE
Fixes 331 and 332: Add continue

### LINKED ISSUE #331: relayer/cmd.filesAdd: seemingly missing continue or wrong message talking about skipping, yet falling through
While reading through this code, I noticed this code https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/cmd/chains.go#L310-L318

The last line says https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/cmd/chains.go#L316
but then falls through and adds file to the chain. Was this intended?

Kindly cc-ing @jackzampolin

### PR DESCRIPTION
**Pull request by PrathyushaLakkireddy**
closes: #331 #332

### CODE REVIEW

File: cmd/chains.go [hunk 1]
```diff
@@ -314,6 +314,7 @@ func filesAdd(dir string) (cfg *Config, err error) {
 				continue
 			}
 			fmt.Printf("%s did not contain valid chain config, skipping...\n", pth)
+			continue
```
Comment (pekis1) [inline cmd/chains.go:317]: Bitcoin

**Review by pekis1 — APPROVED** [review]

**Review by colin-axner — APPROVED** [review]
thanks!

**Comment by pekis1** [comment]
#344
