### PR TITLE
path processor race

### LINKED ISSUE #991: fatal error: concurrent map iteration and map write
When many paths are enabled, there appears to be a concurrent iteration and map write.. likely some unforeseen collission in metrics gathering and multi-path execution.

### PR DESCRIPTION
**Pull request by agouin**
closes #991

### CODE REVIEW

File: relayer/chains/cosmos/cosmos_chain_processor.go [hunk 1]
```diff
@@ -398,12 +398,12 @@ func (ccp *CosmosChainProcessor) queryCycle(ctx context.Context, persistence *qu
 		pp.HandleNewData(chainID, processor.ChainProcessorCacheData{
 			LatestBlock:          ccp.latestBlock,
 			LatestHeader:         latestHeader,
-			IBCMessagesCache:     ibcMessagesCache,
+			IBCMessagesCache:     ibcMessagesCache.Clone(),
```
Comment (DavidNix) [inline relayer/chains/cosmos/cosmos_chain_processor.go:401]: I wonder how this will affect memory consumption. 🤔 

Will memory linearly increase with each path, for example?

Comment (agouin) [reply relayer/chains/cosmos/cosmos_chain_processor.go:401]: The messages not relevant to a given path processor will be filtered out when it does the `mergeMessagesCache` in the `pathEndRuntime`, so there shouldn't be a drastic increase in memory usage from this. Memory usage will definitely increase for more paths, but should be linear based on the ibc tx volume on those paths.

File: relayer/processor/types.go [hunk 2]
```diff
@@ -77,6 +77,15 @@ type IBCMessagesCache struct {
 	ChannelHandshake    ChannelMessagesCache
 }
 
+// Clone makes a deep copy of an IBCMessagesCache.
+func (c IBCMessagesCache) Clone() IBCMessagesCache {
+	x := NewIBCMessagesCache()
```
Comment (mark-rushakoff) [inline relayer/processor/types.go]: This is going to initialize all the maps to a default length. It seems like it would be a worthwhile tradeoff to correctly presize the maps, i.e.

```go
x := IBCMessagesCache{
  PacketFlow: make(ChannelPacketMessagesCache, len(c.PacketFlow)),
  // etc.
}
// Then merge individual fields.
```

This could avoid some unnecessary garbage creation.

**Review by mark-rushakoff — APPROVED** [review]

File: relayer/processor/types.go (hunk 2 above)
Comment (agouin) [reply relayer/processor/types.go]: good catch, done
