### PR TITLE
Query channel state and update slice of open channels accordingly

### LINKED ISSUE #685: keep retrying when failing to query channels in `relayerMainLoop()`
If we fail to query the list of channels for a given connection in `relayerMainLoop()` it would be nice to continue trying to dial if it's already been connected during the same runtime.

### PR DESCRIPTION
**Pull request by jtieri**
This PR moves the query for all the channels on a connection to outside of the main relayer loop so that it is executed only once on startup which reduces the load on the underlying nodes.

Additionally, each time one of our worker goroutines exits we now query for that channels state and ensure that it is still in the open state and if not, we remove it from our slice of channels we are relaying against.

I also bumped up the default timeout time for sending messages because at 10s I was noticing a lot of timeouts in production and removed some ineffective height queries we were performing on retries.

Closes #685

### CODE REVIEW

File: relayer/strategies.go [hunk 1]
```diff
@@ -65,28 +59,52 @@ func relayerMainLoop(ctx context.Context, log *zap.Logger, src, dst *Chain, filt
 			continue
```
Comment (mark-rushakoff) [inline relayer/strategies.go]: If we enter this loop with srcOpenChannels with length 0, or if the last open channel gets shut, the program will be effectively deadlocked in a hot loop. 

Something different needs to happen on `len(srcOpenChannels) == 0`.

File: relayer/strategies.go [hunk 2]
```diff
@@ -65,28 +59,52 @@ func relayerMainLoop(ctx context.Context, log *zap.Logger, src, dst *Chain, filt
...
 				channel.active = true
-				wg.Add(1)
-				go relayUnrelayedPacketsAndAcks(ctx, log, &wg, src, dst, maxTxSize, maxMsgLength, channel, channels)
+				go relayUnrelayedPacketsAndAcks(ctx, log, src, dst, maxTxSize, maxMsgLength, channel, channels)
 			}
 		}
-		wg.Wait()
 
+		// Block here until one of the running goroutines exit.
 		for channel := range channels {
```
Comment (mark-rushakoff) [inline relayer/strategies.go]: Looking at the body of this loop, this would be more appropriately written as `channel, ok := <-channels` because the loop terminates on the first iteration.

File: relayer/strategies.go [hunk 3]
```diff
@@ -65,28 +59,52 @@ func relayerMainLoop(ctx context.Context, log *zap.Logger, src, dst *Chain, filt
...
+
+			// If the channel is no longer in OPEN state then we remove it from the slice of open channels and,
+			// adjust the slice so that there are no gaps.
+			if queryChannelResp.Channel.State != types.OPEN {
+				for i, openChan := range srcOpenChannels {
+					if openChan.channel.ChannelId == channel.channel.ChannelId {
+						srcOpenChannels[i] = srcOpenChannels[len(srcOpenChannels)-1]
+						srcOpenChannels = srcOpenChannels[:len(srcOpenChannels)-1]
+					}
+				}
```
Comment (mark-rushakoff) [inline relayer/strategies.go]: I have to read this block closely every time I go through this code.

Moving an element from the end of the slice to act as a deletion isn't complicated, but `srcOpenChannels` doesn't have any order associated with it, so `map[???]*ActiveChannel` might be more appropriate. Then this block is just `delete(srcOpenChannels, ???)`.

Not a requirement, just something to think about.

**Review by mark-rushakoff — COMMENTED** [review]
Reading through this helped me understand the flow a little better, but there are still some constructs here that need to be cleaned up.

File: relayer/strategies.go (hunk 1 above)
Comment (jtieri) [reply relayer/strategies.go]: Agreed, perhaps for now we just send an error through the `errCh chan<- error` which would effectively terminate the relayer process?

When the refactor for the Chain/Path processor is complete we will be listening for new channels being created/opened so we could loop here until a channel needs to be opened.

File: relayer/strategies.go (hunk 2 above)
Comment (jtieri) [reply relayer/strategies.go]: Changed this according to your suggestion, thanks!

File: relayer/strategies.go (hunk 3 above)
Comment (jtieri) [reply relayer/strategies.go]: This would certainly increase readability and it's not a big change to make so I think I'll include that here as well 👍

File: relayer/strategies.go [hunk 4]
```diff
@@ -32,62 +31,83 @@ func relayerMainLoop(ctx context.Context, log *zap.Logger, src, dst *Chain, filt
...
+				zap.Error(err),
+			)
+		})); err != nil {
+			errCh <- err
+			return
+		}
+
+		// If the channel is no longer in OPEN state then we remove it from the map of open channels.
+		if queryChannelResp.Channel.State != types.OPEN {
+			delete(srcOpenChannels, channel.channel.ChannelId)
```
Comment (mark-rushakoff) [inline relayer/strategies.go:117]: Seems worth logging, if a channel is no longer open.

Then, do we need a special case to check if `len(srcOpenChannels) == 0` again? Right now it will hit the check at the beginning of the for-loop, which isn't exactly accurate if a channel used to be open but now isn't.

File: relayer/strategies.go [hunk 5]
```diff
@@ -32,62 +31,83 @@ func relayerMainLoop(ctx context.Context, log *zap.Logger, src, dst *Chain, filt
...
 		}
-		wg.Wait()
 
-		for channel := range channels {
-			channel.active = false
-			break
+		// Block here until one of the running goroutines exit.
+		channel, ok := <-channels
+		if !ok {
+			errCh <- fmt.Errorf("the (chan *ActiveChannel) was closed and no more values can be written/read")
```
Comment (mark-rushakoff) [inline relayer/strategies.go]: Now I see that this function creates `channels` and nobody else closes it. So it should be okay to drop the `, ok` check here, and drop deferring the channel close on L34.

The next question is, what happens if the main loop is blocking on this channel read and the main context is canceled?

That is, this could change to:

```go
var channel *ActiveChannel
select {
  case channel = <-channels:
    // Keep going.
  case <-ctx.Done():
    // Probably want to wait here for background goroutines to finish,
    // which means restoring the wait group.
    // The context cancelation should quickly propagate to all 
    // relayUnrelayedPacketsAndAcks goroutines.
    wg.Wait()
    errCh <- ctx.Err()
    return
}

channel.active = false
// ...
```

**Review by mark-rushakoff — COMMENTED** [review]
I have two more questions, but I think the readability has improved quite a bit already.

File: relayer/strategies.go (hunk 5 above)
Comment (jtieri) [reply relayer/strategies.go]: Good catch there, went ahead and made the necessary changes so we are handling the main context being cancelled properly.

File: relayer/strategies.go (hunk 4 above)
Comment (jtieri) [reply relayer/strategies.go:117]: I agree, logging here is nice.

Given that sometime in the near future we will likely still loop even if there are no channels open, I think I'd rather revise the error message near the top instead of adding another check on the number of open channels.

File: relayer/strategies.go [hunk 6]
```diff
@@ -186,9 +199,10 @@ func applyChannelFilterRule(filter ChannelFilter, channels []*types.IdentifiedCh
 }
 
 // relayUnrelayedPacketsAndAcks will relay all the pending packets and acknowledgements on both the src and dst chains.
-func relayUnrelayedPacketsAndAcks(ctx context.Context, log *zap.Logger, src, dst *Chain, maxTxSize, maxMsgLength uint64, srcChannel *ActiveChannel, channels chan<- *ActiveChannel) {
+func relayUnrelayedPacketsAndAcks(ctx context.Context, log *zap.Logger, wg *sync.WaitGroup, src, dst *Chain, maxTxSize, maxMsgLength uint64, srcChannel *ActiveChannel, channels chan<- *ActiveChannel) {
 	// make goroutine signal its death, whether it's a panic or a return
 	defer func() {
+		wg.Done()
 		channels <- srcChannel
```
Comment (mark-rushakoff) [inline relayer/strategies.go:206]: One interesting thing I noticed here -- we signal to `wg.Done()` first, which is good because that will unblock the main loop's `wg.Wait()` call. However, it is possible that the following `channels <- srcChannel` send may block if the channel is full.

Up on L33, we initialize `channels` to capacity 10. It is unlikely right now that we will have 10 channels, but I think we can pick a more meaningful value if we initialize it with capacity `len(srcChannels)`.

**Review by mark-rushakoff — APPROVED** [review]
I think this is ready for merge. Probably good to fix the `channels` capacity in the main loop, but that can be separate too.

File: relayer/strategies.go (hunk 6 above)
Comment (jtieri) [reply relayer/strategies.go:206]: Excellent point! I forgot we couldn't do this before because we initialized the channel outside of the loop before we queried the channels but, now that we perform the query outside of the loop too this would be a nice change. Will follow up with a PR to make this change.
