### PR TITLE
fix: Observed Packet Metric

### LINKED ISSUE #1341: Update `cosmos_relayer_observed_packets` metric to only observe packets that apply to filter rules

### PR DESCRIPTION
**Pull request by boojamya**
The main goal of this PR was to fix the `ShouldRelayChannel` method in the case where there was no path filter rule in the relayer config.

We discovered an issue when tracking `cosmos_relayer_observed_packets` metric. When no filter was applied to a path, we were observing packets that were irrelevant to the path(s) the relayer was configured for. 

To fix this we now check if the channelKey is in the `channelStateCache` in the `pathEndRunTime`
 - this is the reason to move `ShouldRelayChannel` from `path_end` to `path_end_runtime`

The unit tests were refactored. 

Closes #1341

### CODE REVIEW

File: relayer/processor/path_end_runtime.go [hunk 1]
```diff
@@ -874,3 +878,41 @@ func (pathEnd *pathEndRuntime) localhostSentinelProofChannel(
 		Version:     info.Version,
 	}, nil
 }
+
```
Comment (jtieri) [inline relayer/processor/path_end_runtime.go:881]: `ShouldRelayChannel` is an exported method so I think it would be cleaner and more idiomatic if the Go doc comment began with the method name and had a bit neater of formatting (e.g. proper use of capital/lowercase letters, punctuation, whitespace, etc.) describing the various cases

**Review by jtieri — APPROVED** [review]
had one nit but otherwise i think this looks sufficient, tests look accurate and the intended patch seems to make sense to me.

gonna approve this now so it's not blocked on me
