### PR TITLE
WIP: relayer start refactor

### LINKED ISSUE #543: relayer start improvements
Currently the relayer has some issues with running via the `rly start [path]` command. 
To address these issues a few things must be tackled

- [ ] Send MsgUpdateClient if there has been no traffic on the channel for some configurable duration of time.
- [ ] Squash bugs/errors to get the main loop working again
    - Pass context down from the cmd to the functions called in Start loop for graceful closing
    - On errors we want to log, not exit

### LINKED ISSUE #556: Relayer start panic
```
rly start hubosmo -d
I[2022-01-17|16:18:20.542] unrelayed sequences error: post failed: Post "http://34.94.61.220:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4ae0c31]

goroutine 6 [running]:
github.com/cosmos/relayer/relayer.StartRelayer.func1()
	/Users/dan/go/src/github.com/cosmos/relayer/relayer/strategies.go:22 +0xf1
created by github.com/cosmos/relayer/relayer.StartRelayer
	/Users/dan/go/src/github.com/cosmos/relayer/relayer/strategies.go:11 +0xc5
```

### PR DESCRIPTION
**Pull request by jtieri**
Working on getting the `rly start [path]` command working as intended

Closes #543 
Closes #556

### CODE REVIEW

File: relayer/naive-strategy.go [hunk 1]
```diff
@@ -380,25 +380,58 @@ func RelayPackets(src, dst *Chain, sp *RelaySequences, maxTxSize, maxMsgLength u
 
 	// Prepend non-empty msg lists with UpdateClient
 	if len(msgs.Dst) != 0 {
```
Comment (jackzampolin) [inline relayer/naive-strategy.go:392]: Maybe wrap this logic up in a function since its repeated?

**Review by jackzampolin — APPROVED** [review]
