### PR TITLE
Provide clearer logging when encountering issues with underlying node

### LINKED ISSUE #762: Better handling/clearer error around node configuration issues
When tx indexing is turned off on a RPC node you see errors logged like this

```
2022-06-01T16:57:38.775794Z     info    Failed to relay packet from sequence    {"src_chain_id": "osmosis-1", "src_channel_id": "channel-165", "src_port_id": "transfer", "dst_chain_id": "sommelier-3", "dst_channel_id": "channel-0", "dst_port_id": "transfer", "channel_order": "ORDER_UNORDERED", "error": "RPC error -32603 - Internal error: transaction indexing is disabled"}
```

It would be beneficial to provide a clearer error so users know to check their nodes configuration

### PR DESCRIPTION
**Pull request by jtieri**
Closes #762

### CODE REVIEW

File: relayer/strategies.go [hunk 1]
```diff
@@ -257,6 +258,19 @@ func relayUnrelayedPackets(ctx context.Context, log *zap.Logger, src, dst *Chain
 			return false
 		}
 
+		// If we encounter an error that suggest node configuration issues, log a more insightful error message.
+		if strings.Contains(err.Error(), "Internal error: transaction indexing is disabled") {
+			log.Warn(
+				"Remote server needs reconfigured.",
```
Comment (mark-rushakoff) [inline relayer/strategies.go]: No punctuation at the end of log messages. Maybe reword to "Remove server needs to enable transaction indexing"?

**Review by mark-rushakoff — APPROVED** [review]
