### PR TITLE
Only validate client and connection identifiers if they are set already.

### LINKED ISSUE #623: rly tx clients/client - dupe commands
`rly transact clients [path-name] [flags]`

`rly transact client [src-chain-id] [dst-chain-id] [path-name] [flags]`

I believe these two commands are doing the same thing.
However, rly tx client does not currently work. Getting the error below.

I think the input arguments of `rly transact clients [path-name] [flags]` make more sense given that the chain-ids are already supplied in the config and you can retrieve them by knowing the path name. No need to pass chain-ids in as args.

**I think we should fix `rly transact clients` and remove `rly transact client`**

Given error:
`Error: path on chain ibc-0 failed to set: identifier cannot be blank: invalid identifier [cosmos/ibc-go/v3@v3.0.0-rc0/modules/core/24-host/validate.go:41]`

### PR DESCRIPTION
**Pull request by jtieri**
`Path` identifiers are attempting to be validated on newly created Paths which don't have clients or connections initialized yet. If this is a blank `Path` we don't want to attempt to validate the identifiers

Closes #623

### CODE REVIEW

File: relayer/ics24.go [hunk 1]
```diff
@@ -52,11 +52,16 @@ func (c *Chain) AddPath(clientID, connectionID string) error {
 
 // ValidateFull returns errors about invalid identifiers as well as unset path variables for the appropriate type
```
Comment (mark-rushakoff) [inline relayer/ics24.go]: Maybe update the godoc here to clarify behavior for zero client/connection ID.

**Review by mark-rushakoff — APPROVED** [review]

File: relayer/ics24.go (hunk 1 above)
Comment (jtieri) [reply relayer/ics24.go]: updated the godoc for all three methods that are being utilized in adding a `Path` to a `Chain`
